server:
  servlet:
    context-path: /nea
  port: 8080

spring:
  main:
    log-startup-info: false
  jackson:
    serialization:
      indent-output: true

nea-gateway:
  url: https://api.nasa.gov
  name: neaGateway
  api_key: you_api_key

logging.level.com.tiagobani.neaapi.gateways.NeaGateway: DEBUG

feign:
  client:
    config:
      default:
        Connecttimeout: 5000
        readTimeout: 5000
        loggerLevel: BASIC